# Numpy Crash Course

In [52]:
import numpy as np

In [53]:
import sys
sys.version

'3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]'

In [54]:
import numpy as np

In [55]:
np.__version__

'1.21.5'

In [56]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [57]:
arr=np.array(my_list)

In [58]:
arr

array([0, 1, 2, 3, 4, 5])

In [59]:
type(arr)

numpy.ndarray

In [60]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [61]:
np.range()

AttributeError: module 'numpy' has no attribute 'range'

In [62]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [65]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [66]:
np.arange(10,30,30,3)

TypeError: Cannot interpret '3' as a data type

In [67]:
np.arange(10,30,30,3)

TypeError: Cannot interpret '3' as a data type

In [68]:
np.arange(20,8)

array([], dtype=int32)

In [69]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [71]:
n= np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [72]:
np.zeros(3)

array([0., 0., 0.])

In [73]:
np.zeros(3, dtype= int)

array([0, 0, 0])

In [74]:
z=np.zeros(10)

In [75]:
z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
nd=np.zeros((5,9), dtype=int)

In [80]:
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [81]:
np.ones(3)

array([1., 1., 1.])

In [82]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [83]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [84]:
np.three(3)

AttributeError: module 'numpy' has no attribute 'three'

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [87]:
rand(3,2)

NameError: name 'rand' is not defined

In [89]:
random.rand(2)

NameError: name 'random' is not defined

In [91]:
np.random.rand(2)

array([0.70998292, 0.6917234 ])

In [92]:
np.random.rand(3)

array([0.67924671, 0.71160243, 0.81364841])

In [93]:
np.random.rand(2,3)

array([[0.00162226, 0.86040397, 0.0547757 ],
       [0.87816271, 0.28542323, 0.07140391]])

In [94]:
np.random.randint(3)

1

In [95]:
np.random.randint(2,10) #2 is inclusive ,10 is exclusive

9

In [96]:
np.random.randint(2,10)

6

In [97]:
np.random.randint(2,10,4)

array([4, 8, 8, 2])

In [98]:
np.random.randint(-30,10,10)

array([  5,   1,   5,   6,   7,   2, -18,   4,  -7,  -9])

In [99]:
np.random.randint(10,40,(10,10))

array([[18, 23, 38, 19, 11, 29, 17, 25, 36, 33],
       [30, 27, 17, 19, 22, 10, 35, 14, 12, 10],
       [25, 39, 32, 26, 37, 32, 18, 27, 32, 27],
       [23, 32, 36, 16, 12, 31, 36, 19, 21, 20],
       [12, 31, 23, 13, 20, 24, 24, 28, 18, 13],
       [11, 39, 37, 12, 10, 33, 27, 16, 31, 29],
       [31, 23, 36, 31, 10, 10, 25, 29, 24, 39],
       [32, 26, 17, 13, 28, 36, 15, 25, 10, 30],
       [11, 32, 39, 16, 18, 24, 27, 13, 37, 39],
       [38, 20, 10, 18, 39, 16, 30, 32, 13, 27]])

In [100]:
m=np.random.randint(10,40,(10,10))
m

array([[17, 37, 36, 33, 23, 11, 18, 20, 21, 24],
       [28, 11, 10, 33, 23, 31, 39, 36, 37, 38],
       [26, 26, 28, 35, 32, 32, 31, 30, 24, 36],
       [38, 11, 25, 39, 19, 39, 22, 37, 24, 19],
       [32, 24, 19, 23, 28, 30, 15, 27, 11, 36],
       [13, 28, 37, 32, 24, 17, 18, 12, 12, 36],
       [26, 14, 16, 30, 38, 30, 17, 17, 33, 22],
       [27, 11, 24, 36, 20, 34, 23, 28, 22, 37],
       [21, 33, 18, 24, 25, 15, 22, 25, 21, 35],
       [12, 21, 19, 16, 14, 38, 18, 28, 33, 36]])

In [101]:
arr

array([0, 1, 2, 3, 4, 5])

In [102]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [104]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [105]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

# slicing in matrix

In [106]:
m

array([[17, 37, 36, 33, 23, 11, 18, 20, 21, 24],
       [28, 11, 10, 33, 23, 31, 39, 36, 37, 38],
       [26, 26, 28, 35, 32, 32, 31, 30, 24, 36],
       [38, 11, 25, 39, 19, 39, 22, 37, 24, 19],
       [32, 24, 19, 23, 28, 30, 15, 27, 11, 36],
       [13, 28, 37, 32, 24, 17, 18, 12, 12, 36],
       [26, 14, 16, 30, 38, 30, 17, 17, 33, 22],
       [27, 11, 24, 36, 20, 34, 23, 28, 22, 37],
       [21, 33, 18, 24, 25, 15, 22, 25, 21, 35],
       [12, 21, 19, 16, 14, 38, 18, 28, 33, 36]])

In [107]:
b=np.random.randint(10,20,(5,4))
b

array([[19, 17, 16, 15],
       [16, 11, 15, 16],
       [11, 16, 14, 18],
       [19, 15, 13, 17],
       [11, 18, 17, 18]])

In [108]:
b[:]

array([[19, 17, 16, 15],
       [16, 11, 15, 16],
       [11, 16, 14, 18],
       [19, 15, 13, 17],
       [11, 18, 17, 18]])

In [109]:
b[1:4]

array([[16, 11, 15, 16],
       [11, 16, 14, 18],
       [19, 15, 13, 17]])

In [110]:
b[-1:]

array([[11, 18, 17, 18]])

In [111]:
b[:-1]

array([[19, 17, 16, 15],
       [16, 11, 15, 16],
       [11, 16, 14, 18],
       [19, 15, 13, 17]])

In [112]:
b[1,3]

16

In [113]:
arr

array([0, 1, 2, 3, 4, 5])

In [114]:
b

array([[19, 17, 16, 15],
       [16, 11, 15, 16],
       [11, 16, 14, 18],
       [19, 15, 13, 17],
       [11, 18, 17, 18]])

In [115]:
b[0,3]

15

In [116]:
b[0,-3]

17

In [117]:
b[2,3]

18

In [118]:
b[-1,-1]

18

In [119]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
np.ones((3,4),dtype=int).reshape(4,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [121]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [122]:
b

array([[19, 17, 16, 15],
       [16, 11, 15, 16],
       [11, 16, 14, 18],
       [19, 15, 13, 17],
       [11, 18, 17, 18]])

In [123]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37],
       [95, 52,  2, 61, 61, 33, 76, 55, 34, 91],
       [82, 57, 83, 28,  9, 48,  9,  0, 33, 91],
       [93, 48,  6, 63, 87, 69, 81, 84, 27, 29],
       [62, 38, 17, 11, 86, 71, 75,  9, 86, 94],
       [ 9, 43, 92, 41, 41, 49, 41, 58, 84, 91]])

In [124]:
arr2[0:5]

array([[ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37]])

In [125]:
arr2

array([[ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37],
       [95, 52,  2, 61, 61, 33, 76, 55, 34, 91],
       [82, 57, 83, 28,  9, 48,  9,  0, 33, 91],
       [93, 48,  6, 63, 87, 69, 81, 84, 27, 29],
       [62, 38, 17, 11, 86, 71, 75,  9, 86, 94],
       [ 9, 43, 92, 41, 41, 49, 41, 58, 84, 91]])

In [126]:
arr2[1,4]

33

In [127]:
arr2[-5,5]

33

In [128]:
arr2[-5,-5]

33

In [129]:
arr2[::-1]

array([[ 9, 43, 92, 41, 41, 49, 41, 58, 84, 91],
       [62, 38, 17, 11, 86, 71, 75,  9, 86, 94],
       [93, 48,  6, 63, 87, 69, 81, 84, 27, 29],
       [82, 57, 83, 28,  9, 48,  9,  0, 33, 91],
       [95, 52,  2, 61, 61, 33, 76, 55, 34, 91],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3],
       [ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32]])

In [130]:
arr2[::-2]

array([[ 9, 43, 92, 41, 41, 49, 41, 58, 84, 91],
       [93, 48,  6, 63, 87, 69, 81, 84, 27, 29],
       [95, 52,  2, 61, 61, 33, 76, 55, 34, 91],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3]])

In [131]:
arr2[::2]

array([[ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37],
       [82, 57, 83, 28,  9, 48,  9,  0, 33, 91],
       [62, 38, 17, 11, 86, 71, 75,  9, 86, 94]])

In [132]:
arr2

array([[ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37],
       [95, 52,  2, 61, 61, 33, 76, 55, 34, 91],
       [82, 57, 83, 28,  9, 48,  9,  0, 33, 91],
       [93, 48,  6, 63, 87, 69, 81, 84, 27, 29],
       [62, 38, 17, 11, 86, 71, 75,  9, 86, 94],
       [ 9, 43, 92, 41, 41, 49, 41, 58, 84, 91]])

In [133]:
arr2[:-3]

array([[ 2, 49, 11, 23, 45, 46, 24, 14, 86, 32],
       [49, 71, 88, 86, 33,  0, 53, 58, 20,  3],
       [11, 91, 68, 89, 53, 52, 78, 30, 91, 48],
       [53,  6, 46, 56, 97, 75, 96, 59, 24, 12],
       [14, 20,  3, 54, 92, 41, 66, 55, 83, 37],
       [95, 52,  2, 61, 61, 33, 76, 55, 34, 91],
       [82, 57, 83, 28,  9, 48,  9,  0, 33, 91]])

In [134]:
arr

array([0, 1, 2, 3, 4, 5])

In [135]:
arr.max()

5

In [136]:
arr.min()

0

In [137]:
arr.mean()

2.5

In [138]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [139]:
from numpy import*
a= array([1,2,3,4,9])
a

array([1, 2, 3, 4, 9])

In [140]:
arr=np.array([0,6])
arr

array([0, 6])

In [141]:
a

array([1, 2, 3, 4, 9])

In [142]:
median(a)

3.0

In [143]:
arr=array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [144]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [145]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [146]:
arr.reshape(2,3,order='F')  

array([[0, 2, 4],
       [1, 3, 5]])

In [147]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [148]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
c=array([0,1,2,3,4,5,])
c

array([0, 1, 2, 3, 4, 5])

In [150]:
c.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
c.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [152]:
c.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

# indexing

In [153]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [154]:
row=4
col=5

In [155]:
row

4

In [156]:
col

5

In [157]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
mat[row,col]

45

In [159]:
col=6

In [160]:
mat[row,col]

46

In [161]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [162]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [163]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [164]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [166]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
mat[0:10:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [168]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [170]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[2:4,2:4]

array([[22, 23],
       [32, 33]])

In [173]:
mat[2:5,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [174]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [175]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [176]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [177]:
mat[mat==50]

array([50])

In [178]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])