In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
newarr1=arr.reshape(2,3,2)
newarr2=arr.reshape(4,3)
print(newarr1)
print(newarr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [6]:
newarr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
newarr1=[...,2]
print(newarr1)

[Ellipsis, 2]


In [8]:
newarr1=[1,...]
print(newarr1)

[1, Ellipsis]


In [9]:
b=np.arange(0,20)

In [10]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
b1=b.reshape(5,4)

In [12]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
b1[0,0]

np.int64(0)

In [14]:
b1[-1]

array([16, 17, 18, 19])

In [15]:
b1[1:3,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [16]:
b1>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [17]:
mat=np.arange(0,20).reshape(5,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
mat>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [19]:
b1<=15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [20]:
 a = np.array([[ 0, 1, 2, 3, 4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34]])
 c = np.array( [True,False,True,False] )  # boolean row selector
print(a)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [21]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [22]:
d =  np.array([False,True,True,False,True]) # boolean column selector
a[:,d]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [23]:
 i = np.array([0, 1, 2, 1]) # array of indices for the first axis
 j = np.array([1,2,3,4]) # array of indices for the second axis

In [24]:
a[i,j]

array([ 1, 12, 23, 14])

# abs() & 4. ABSOLUTE - both are same- Synonym for abs()


In [25]:
import numpy as np
ARR = np.arange(-4,5).reshape(3,3)
ARR

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [26]:
ARR1 = 1.2+5j
ARR1

(1.2+5j)

In [27]:
abs(ARR1) #UNNDER-ROOT OF Square of of real part & imaginary part

5.141984052872976

In [28]:
np.absolute(ARR1)

np.float64(5.141984052872976)

In [29]:
np.absolute([-10, -15])

array([10, 15])

# accumulate

In [30]:
import numpy as np

In [31]:
A1= np.arange(0,10)
A1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.add.accumulate(A1)  # Progressive SUM 

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [33]:
A2 = np.arange(1,6)
A2

array([1, 2, 3, 4, 5])

In [34]:
np.multiply.accumulate(A2)

array([  1,   2,   6,  24, 120])

In [35]:
AC = np.array([[1,2,3],[4,5,6]])
AC

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.add.accumulate(AC) # EVERY COLOMN GOT ACCUMULATE

array([[1, 2, 3],
       [5, 7, 9]])

In [37]:
np.multiply.accumulate(AC)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

# add

In [38]:
import numpy as np

In [39]:
ar1 = [2, -6]
ar2 = [1, 3]
ar3 = [2.2, 8.7]
ar4 = [7, -3]
print(ar1, ar2, ar3,  ar4)

[2, -6] [1, 3] [2.2, 8.7] [7, -3]


In [40]:
np.add(ar1, ar2)

array([ 3, -3])

In [41]:
np.add(ar3, ar4)

array([9.2, 5.7])

In [42]:
C1 = 5+2j

In [43]:
np.add(ar3, C1)

array([ 7.2+2.j, 13.7+2.j])

# all

In [44]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.all(a>5)

np.False_

In [46]:
np.all(a>=0)

np.True_

In [47]:
b7 = np.array([True, False, True, True])
np.all(b7)

np.False_

# allclose

In [48]:
np.allclose([0.1, 0.003], [0.11, 0.003])

False

In [49]:
np.allclose([0.11, 0.0033], [0.11000005, 0.00330001])

True

In [50]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [51]:
a = np.array([1, 5, 2, 7])
np.all(a >= 5)

np.False_

# angle

In [52]:
np.angle([5+3j, 1j, 1.0], deg=True)# in Degree

array([30.96375653, 90.        ,  0.        ])

In [53]:
np.angle(1+1j,deg=True)

np.float64(45.0)

In [54]:
np.angle(1+1j,deg=False)

np.float64(0.7853981633974483)

# any

In [55]:
c2 = np.array([True, False, True])

In [56]:
np.any(c2)

np.True_

In [57]:
c3= np.arange(0,10)
c3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
any(c3>=5)

True

# append

In [59]:
c3= np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

In [60]:
c3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
c5=np.append(c3,10)
c5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
np.append(c5, ('ABC', 1 +2j))

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'ABC', '(1+2j)'],
      dtype='<U64')

In [63]:
c9= np.arange(10, 61, 10)
c9

array([10, 20, 30, 40, 50, 60])

In [64]:
np.append(c9, (70, 80, 90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
c10 =np.reshape(c9, (2,3))
c10

array([[10, 20, 30],
       [40, 50, 60]])

In [66]:
c11 = np.append(c10, [[70, 80, 90]], axis = 0)  # AT ROw
c11

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [67]:
c13 = np.append(c11, [[100], [120], [130]], axis = 1) # AT COLUMN
c13

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 120],
       [ 70,  80,  90, 130]])

# apply_along_axis  It will apply function to axis

In [68]:
def func1(Q): #EX-1
    return (Q[0] + Q[-1])
abc = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
 np.apply_along_axis(func1,0,abc)

array([ 8, 10, 12])

In [70]:
 np.apply_along_axis(func1,1,abc)

array([ 4, 10, 16])

In [71]:
def func2(P): #2
 return (P[0] + P[-1])*2
abc1 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.apply_along_axis(func2,0,abc1)

array([16, 20, 24])

In [73]:
np.apply_along_axis(func2,1,abc1)

array([ 8, 20, 32])

# apply_over_axes()

In [74]:
D = np.arange(24)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
D=np.reshape(D, (2,3,4))
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
DQ = np.apply_over_axes(np.sum, D, [0,2]) # sum over all axes except axis=1
DQ

array([[[ 60],
        [ 92],
        [124]]])

# arrange

In [77]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
np.arange(11.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [79]:
np.arange(8, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [80]:
np.arange(5,10) # start,stop

array([5, 6, 7, 8, 9])

In [81]:
np.arange(3,30,9) # start,stop,step

array([ 3, 12, 21])

# arccos

In [82]:
np.arccos([1, -1])#The inverse of cos so that, if y = cos(x), then x = arccos(y)

array([0.        , 3.14159265])

# arccosh

In [83]:
np.arccosh([np.e, 10.0])# Inverse hyperbolic cosine

array([1.65745445, 2.99322285])

In [84]:
np.arccosh(1)

np.float64(0.0)

# arcsin

In [85]:
np.arcsin([1, -1, 0])

array([ 1.57079633, -1.57079633,  0.        ])

# arcsinh

In [86]:
np.arcsinh([np.e, 10.0])

array([1.72538256, 2.99822295])

# arctan

In [87]:
np.arctan([0, 1, -1])#The inverse of tan, so that if y = tan(x) then x = arctan(y).

array([ 0.        ,  0.78539816, -0.78539816])

# arctan2

In [88]:
x = np.array([-1, +1, +1, -1])
y = np.array([-1, -1, +1, +1])
np.arctan2(y, x) * 180 / np.pi # In Degree Unit

array([-135.,  -45.,   45.,  135.])

In [89]:
np.arctan2(y, x) # IN radian Unit

array([-2.35619449, -0.78539816,  0.78539816,  2.35619449])

In [90]:
np.arctan2([1., -1.], [0., 0.])

array([ 1.57079633, -1.57079633])

In [91]:
np.arctan2([0, 1], [1, 0])

array([0.        , 1.57079633])

# arctanh

In [92]:
np.arctanh([0, -0.5])# Inverse hyperbolic tangent

array([ 0.        , -0.54930614])

# argmax

In [93]:
J =np.array([0, 11, 95, 2, -5, 55]) 

In [94]:
np.argmax(J) # Returns the indices of the maximum values along an axis.

np.int64(2)

In [95]:
j1 = np.arange(6).reshape(2,3) +10
j1

array([[10, 11, 12],
       [13, 14, 15]])

In [96]:
np.argmax(j1)

np.int64(5)

In [97]:
j2=np.array([[10,50,30],[60,20,60]]) 
np.argmax(j2)

np.int64(3)

In [98]:
J2 = np.array([[1, 9, 0, 4], [2, 0, 8, -1]])
J2

array([[ 1,  9,  0,  4],
       [ 2,  0,  8, -1]])

In [99]:
np.argmax(J2, axis =0) 

array([1, 0, 1, 0])

In [100]:
np.argmax(J2, axis=1)

array([1, 2])

# argmin

In [102]:
d4 =np.array([0, 11, 95, 2, -5, 55]) 
#Returns the indices of the Minimum values along an axis.

In [103]:
np.argmin(d4)

np.int64(4)

In [104]:
d9 = np.arange(6).reshape(2,3) +10
d9

array([[10, 11, 12],
       [13, 14, 15]])

In [106]:
np.argmin(d9)

np.int64(0)

In [107]:
da2=np.array([[50,50,10],[60,10,40]])
da2

array([[50, 50, 10],
       [60, 10, 40]])

In [108]:
np.argmin(da2) 

np.int64(2)

# argsoft

In [109]:
AB1 = np.array([ 2, 0,  1, 5, 4, 1, 9])
#Returns the indices that would sort an array

In [111]:
np.argsort(AB1)

array([1, 2, 5, 0, 4, 3, 6])

In [113]:
BQ = np.argsort(AB1)# FOR SORTING OF VALUES
BQ

array([1, 2, 5, 0, 4, 3, 6])

In [115]:
AB1[BQ]

array([0, 1, 1, 2, 4, 5, 9])

In [116]:
aq1 = np.array([[8,4,1],[2,0,9]])
aq1

array([[8, 4, 1],
       [2, 0, 9]])

In [117]:
JQ1 = aq1.argsort(axis=0) # sorts on columns. 
JQ1


array([[1, 1, 0],
       [0, 0, 1]])

In [118]:
aq1[JQ1,[[0,1,2], [0,1,2]]] 

array([[2, 0, 1],
       [8, 4, 9]])

In [119]:
JQ1 = aq1.argsort(axis=1) 
JQ1 

array([[2, 1, 0],
       [1, 0, 2]])

# array

In [121]:
#To Create an array
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [122]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [124]:
np.array([1, 2, 3], dtype=complex) 

array([1.+0.j, 2.+0.j, 3.+0.j])

In [125]:
np.array([1, 2, 3], ndmin=2) 

array([[1, 2, 3]])

In [128]:
np.array(1, subok=1, ndmin=2)

array([[1]])

# array split

In [129]:
c4 = np.array([[1,2,3,4],[5,6,7,8]])
c4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
np.array_split(c4,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [131]:
np.array_split(c4,4,axis=1) 

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [132]:
np.array_split(c4,3,axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [133]:
np.array_split(c4,[2,3],axis=1) 

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

# asarray

In [135]:
my_list = [1, 3, 5, 7, 9]
np.asarray(my_list)

array([1, 3, 5, 7, 9])

In [136]:
my_tuple = ([1, 3, 9], [8, 2, 6])
np.asarray(my_tuple) 

array([[1, 3, 9],
       [8, 2, 6]])

In [138]:
m = np.matrix('1 2; 5 8') 
m

matrix([[1, 2],
        [5, 8]])

In [139]:
B9 = np.asarray(m)
B9

array([[1, 2],
       [5, 8]])

In [140]:
m[0,1] = -190
m

matrix([[   1, -190],
        [   5,    8]])

In [147]:
B9

array([[   1, -190],
       [   5,    8]])

# asanyarray

In [144]:
c7 = np.array([[1,2],[5,8]])
c7

array([[1, 2],
       [5, 8]])

In [150]:
mq = np.matrix('1 2; 5 8')
mq

matrix([[1, 2],
        [5, 8]])

In [151]:
np.asanyarray(c7)

array([[1, 2],
       [5, 8]])

# asmatrix

In [154]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [155]:
x[0,0] = 5
print(m)

print(x)

[[5 2]
 [3 4]]
[[5 2]
 [3 4]]


# astype

In [157]:
x6 = np.array([1, 2, 2.5])
x6

array([1. , 2. , 2.5])

In [158]:
x6 = np.array([1, 2, 2.5],dtype=int)
x6

array([1, 2, 2])

In [159]:
x6.astype(int)

array([1, 2, 2])

In [160]:
x6.astype(None) 

array([1., 2., 2.])

# atleast 1d

In [161]:
 a01 = 1 # 0-d array
 b01 = np.array([2,3]) # 1-d array
 c01 = np.array([[4,5],[6,7]]) # 2-d array
 d01 = np.arange(8).reshape(2,2,2) # 3-d array
 d01

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [162]:
np.atleast_1d(a01,b01,c01,d01) 

(array([1]),
 array([2, 3]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

# atleast_2d()

In [163]:
 a11 = 1 # 0-d array
 b11 = np.array([2,3]) # 1-d array
 c11 = np.array([[4,5],[6,7]]) # 2-d array
 d11 = np.arange(8).reshape(2,2,2) # 3-d array
 d11

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [164]:
np.atleast_2d(a11,b11,c11,d11)

(array([[1]]),
 array([[2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

# atleast_3d()

In [165]:
 f = 1 # 0-d array
 g = np.array([2,3]) # 1-d array
 h = np.array([[4,5],[6,7]]) # 2-d array
 i = np.arange(8).reshape(2,2,2) # 3-d array
 i

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [166]:
np.atleast_3d(f,g,h,i)

(array([[[1]]]),
 array([[[2],
         [3]]]),
 array([[[4],
         [5]],
 
        [[6],
         [7]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))